# Generated by Django 5.2.5 on 2025-09-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_imagem_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preco_antigo',
            new_name='preco_original',
        ),
        migrations.AddField(
            model_name='produto',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
